apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: windows-exporter-servicemonitor
  namespace: default
  labels:
    release: prometheus
    app: prometheus
spec:
  jobLabel: job
  selector:
    matchLabels:
      app: windows-exporter
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: http
      interval: 30s
      path: "/metrics"