apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prometheus-ingress
  namespace: monitoring
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    # IP Whitelisting
    nginx.ingress.kubernetes.io/whitelist-source-range: "<Your_Grafana_Instance_IP>/32"
spec:
  tls:
  - hosts:
    - prometheus-region1.mycompany.com
    secretName: prometheus-tls
  rules:
  - host: prometheus-region1.mycompany.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: prometheus-kube-prometheus-stack-prometheus
            port:
              number: 9090